// <auto-generated />
using System;
using InternshipEntryTask.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternshipEntryTask.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternshipEntryTask.Infrastructure.Models.GameModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AccessKeyPlayerO")
                        .HasColumnType("uuid")
                        .HasColumnName("anonymous_player_o_id");

                    b.Property<Guid?>("AccessKeyPlayerX")
                        .HasColumnType("uuid")
                        .HasColumnName("anonymous_player_x_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("JoinKey")
                        .HasColumnType("uuid")
                        .HasColumnName("join_key");

                    b.Property<string>("LastMoveHash")
                        .HasColumnType("text");

                    b.Property<int>("NextMove")
                        .HasColumnType("integer")
                        .HasColumnName("next_move");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("AccessKeyPlayerO")
                        .IsUnique();

                    b.HasIndex("AccessKeyPlayerX")
                        .IsUnique();

                    b.HasIndex("JoinKey")
                        .IsUnique();

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("InternshipEntryTask.Infrastructure.Models.MoveModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccessKeyPlayer")
                        .HasColumnType("uuid")
                        .HasColumnName("access_key_player");

                    b.Property<int>("CellValue")
                        .HasColumnType("integer")
                        .HasColumnName("cell_value");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<int>("MoveIndex")
                        .HasColumnType("integer")
                        .HasColumnName("move_index");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("moves", (string)null);
                });

            modelBuilder.Entity("InternshipEntryTask.Infrastructure.Models.MoveModel", b =>
                {
                    b.HasOne("InternshipEntryTask.Infrastructure.Models.GameModel", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("InternshipEntryTask.Infrastructure.Models.GameModel", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
